### ISSUE TITLE
加解密服务器运算失败

### ISSUE THREAD

**Issue by ruiyuge** [4532sde/FOXRUN#2]
求助大佬
![屏幕截图 2024-10-19 133535](https://github.com/user-attachments/assets/d60deea9-b851-42d1-9455-4b9104831544)

**Comment by 4532sde** [comment]
感谢issue，
我们暂时关闭了服务器，但是脚本中并未正常展示服务器提示，这是个bug，我们会着手修复。
加解密服务器预计10/20上线，并放宽限制，1ip/10times/1day。

**Comment by EnderWolf006** [comment]
我是从另一个仓库来的，另一个哥们代码里说联系他但是没有联系方式，大佬能给一个不，交流脚本开发
