### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by EnderWolf006** [4532sde/FOXRUN#3]
![image](https://github.com/user-attachments/assets/5b2b6843-eb4f-4b10-b79a-bcb6c20f3c6d)
顺便问大佬要个联系方式，我也是写脚本的，一起交流一下

**Comment by 4532sde** [comment]
暂不公开联系方式

**Comment by iceylia-unicorn** [comment]
我也是这个问题，大佬是停止运行这个项目了吗
